[project]
name = "数据库测试"
version = "0.1.0"
description = "测试sqlite数据库能否实现"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fletx>=0.2.0",
    "requests>=2.32.4",
    "sqlmodel>=0.0.24",
]
authors = [{name = "Flet Developer", email = "your@email.com"}]
