[project]
name = "flet"
version = "0.1.0"
description = "sqlitetest"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet",
    "fletx>=0.2.0",
    "requests>=2.32.4",
    "sqlalchemy",
]
